export const FETCH_PACIENTS_REQUETS = 'FETCH_PACIENTS_REQUETS';
export const FETCH_PACIENTS_SUCCESS = 'FETCH_PACIENTS_SUCCESS';
export const FETCH_PACIENTS_FAILURE = 'FETCH_PACIENTS_FAILURE';
export const CURRENT_PACIENT_STATUS = 'CURRENT_PACIENT_STATUS';